// 100 Test Users - Ready to use seed data
const seedUsers = [
  // ADMIN USERS (5)
  { email: "admin1@platform.com", password: "admin123", role: "admin" },
  { email: "admin2@platform.com", password: "secure456", role: "admin" },
  { email: "superadmin@platform.com", password: "manager789", role: "admin" },
  { email: "admin.chief@platform.com", password: "welcome123", role: "admin" },
  {
    email: "platform.admin@platform.com",
    password: "testing456",
    role: "admin",
  },

  // ORGANIZATION USERS (20)
  {
    email: "director@redcross.org",
    password: "redcross2024",
    role: "organization",
  },
  {
    email: "manager@habitat.org",
    password: "buildHomes",
    role: "organization",
  },
  {
    email: "coordinator@foodbank.org",
    password: "coordinate789",
    role: "organization",
  },
  {
    email: "admin@unitedway.org",
    password: "unitedway1",
    role: "organization",
  },
  {
    email: "director@salvation.org",
    password: "salvation24",
    role: "organization",
  },
  { email: "lead@ymca.org", password: "ymcaLeader", role: "organization" },
  { email: "head@goodwill.org", password: "goodwill123", role: "organization" },
  {
    email: "manager@shelter.org",
    password: "shelterMgr",
    role: "organization",
  },
  {
    email: "org.admin@charity.org",
    password: "charity456",
    role: "organization",
  },
  {
    email: "director@nonprofit.org",
    password: "nonprofit1",
    role: "organization",
  },
  {
    email: "coord@community.org",
    password: "community24",
    role: "organization",
  },
  {
    email: "leader@foundation.org",
    password: "foundation1",
    role: "organization",
  },
  {
    email: "manager@animalrescue.org",
    password: "rescue123",
    role: "organization",
  },
  {
    email: "admin@foodpantry.org",
    password: "foodhelp1",
    role: "organization",
  },
  {
    email: "director@homeless.org",
    password: "homeless24",
    role: "organization",
  },
  { email: "coord@veterans.org", password: "veterans1", role: "organization" },
  {
    email: "manager@seniors.org",
    password: "seniors123",
    role: "organization",
  },
  { email: "lead@youth.org", password: "youth2024", role: "organization" },
  {
    email: "admin@environment.org",
    password: "green123",
    role: "organization",
  },
  {
    email: "director@education.org",
    password: "education1",
    role: "organization",
  },

  // VOLUNTEER USERS (75)
  {
    email: "sarah.johnson@gmail.com",
    password: "volunteer1",
    role: "volunteer",
  },
  { email: "mike.davis@yahoo.com", password: "helper123", role: "volunteer" },
  {
    email: "emily.wilson@hotmail.com",
    password: "emily2024",
    role: "volunteer",
  },
  { email: "john.smith@gmail.com", password: "johnvol1", role: "volunteer" },
  { email: "lisa.brown@outlook.com", password: "lisa456", role: "volunteer" },
  { email: "david.miller@gmail.com", password: "david123", role: "volunteer" },
  {
    email: "jennifer.garcia@yahoo.com",
    password: "jennifer1",
    role: "volunteer",
  },
  {
    email: "robert.martinez@gmail.com",
    password: "robert24",
    role: "volunteer",
  },
  {
    email: "maria.rodriguez@hotmail.com",
    password: "maria123",
    role: "volunteer",
  },
  {
    email: "james.taylor@outlook.com",
    password: "james456",
    role: "volunteer",
  },
  { email: "anna.anderson@gmail.com", password: "anna2024", role: "volunteer" },
  {
    email: "michael.thomas@yahoo.com",
    password: "michael1",
    role: "volunteer",
  },
  {
    email: "jessica.jackson@gmail.com",
    password: "jessica24",
    role: "volunteer",
  },
  {
    email: "william.white@hotmail.com",
    password: "william1",
    role: "volunteer",
  },
  {
    email: "ashley.harris@outlook.com",
    password: "ashley123",
    role: "volunteer",
  },
  {
    email: "christopher.martin@gmail.com",
    password: "chris456",
    role: "volunteer",
  },
  {
    email: "amanda.thompson@yahoo.com",
    password: "amanda24",
    role: "volunteer",
  },
  {
    email: "matthew.garcia@gmail.com",
    password: "matthew1",
    role: "volunteer",
  },
  {
    email: "stephanie.lee@hotmail.com",
    password: "steph123",
    role: "volunteer",
  },
  {
    email: "andrew.clark@outlook.com",
    password: "andrew24",
    role: "volunteer",
  },
  { email: "nicole.lewis@gmail.com", password: "nicole456", role: "volunteer" },
  {
    email: "joshua.walker@yahoo.com",
    password: "joshua123",
    role: "volunteer",
  },
  { email: "rachel.hall@gmail.com", password: "rachel24", role: "volunteer" },
  {
    email: "daniel.allen@hotmail.com",
    password: "daniel456",
    role: "volunteer",
  },
  {
    email: "heather.young@outlook.com",
    password: "heather1",
    role: "volunteer",
  },
  { email: "kevin.king@gmail.com", password: "kevin123", role: "volunteer" },
  {
    email: "michelle.wright@yahoo.com",
    password: "michelle24",
    role: "volunteer",
  },
  { email: "brian.lopez@gmail.com", password: "brian456", role: "volunteer" },
  { email: "kimberly.hill@hotmail.com", password: "kim123", role: "volunteer" },
  { email: "jason.green@outlook.com", password: "jason24", role: "volunteer" },
  { email: "laura.adams@gmail.com", password: "laura456", role: "volunteer" },
  { email: "ryan.baker@yahoo.com", password: "ryan123", role: "volunteer" },
  { email: "megan.gonzalez@gmail.com", password: "megan24", role: "volunteer" },
  {
    email: "tyler.nelson@hotmail.com",
    password: "tyler456",
    role: "volunteer",
  },
  {
    email: "crystal.carter@outlook.com",
    password: "crystal1",
    role: "volunteer",
  },
  {
    email: "jacob.mitchell@gmail.com",
    password: "jacob123",
    role: "volunteer",
  },
  { email: "samantha.perez@yahoo.com", password: "sam24", role: "volunteer" },
  { email: "aaron.roberts@gmail.com", password: "aaron456", role: "volunteer" },
  {
    email: "brittany.turner@hotmail.com",
    password: "brittany1",
    role: "volunteer",
  },
  {
    email: "nathan.phillips@outlook.com",
    password: "nathan123",
    role: "volunteer",
  },
  {
    email: "vanessa.campbell@gmail.com",
    password: "vanessa24",
    role: "volunteer",
  },
  {
    email: "jordan.parker@yahoo.com",
    password: "jordan456",
    role: "volunteer",
  },
  { email: "tiffany.evans@gmail.com", password: "tiffany1", role: "volunteer" },
  {
    email: "brandon.edwards@hotmail.com",
    password: "brandon24",
    role: "volunteer",
  },
  {
    email: "christina.collins@outlook.com",
    password: "christina1",
    role: "volunteer",
  },
  { email: "scott.stewart@gmail.com", password: "scott123", role: "volunteer" },
  { email: "amy.sanchez@yahoo.com", password: "amy456", role: "volunteer" },
  {
    email: "jonathan.morris@gmail.com",
    password: "jonathan1",
    role: "volunteer",
  },
  {
    email: "monica.rogers@hotmail.com",
    password: "monica24",
    role: "volunteer",
  },
  {
    email: "jeremy.reed@outlook.com",
    password: "jeremy123",
    role: "volunteer",
  },
  { email: "kayla.cook@gmail.com", password: "kayla456", role: "volunteer" },
  { email: "austin.bailey@yahoo.com", password: "austin24", role: "volunteer" },
  {
    email: "denise.rivera@gmail.com",
    password: "denise123",
    role: "volunteer",
  },
  { email: "adam.cooper@hotmail.com", password: "adam456", role: "volunteer" },
  {
    email: "julie.richardson@outlook.com",
    password: "julie24",
    role: "volunteer",
  },
  { email: "sean.cox@gmail.com", password: "sean123", role: "volunteer" },
  {
    email: "leslie.howard@yahoo.com",
    password: "leslie456",
    role: "volunteer",
  },
  { email: "marcus.ward@gmail.com", password: "marcus24", role: "volunteer" },
  {
    email: "crystal.torres@hotmail.com",
    password: "crystal24",
    role: "volunteer",
  },
  {
    email: "erik.peterson@outlook.com",
    password: "erik123",
    role: "volunteer",
  },
  { email: "cynthia.gray@gmail.com", password: "cynthia1", role: "volunteer" },
  { email: "alex.ramirez@yahoo.com", password: "alex456", role: "volunteer" },
  { email: "mariah.james@gmail.com", password: "mariah24", role: "volunteer" },
  {
    email: "derek.watson@hotmail.com",
    password: "derek123",
    role: "volunteer",
  },
  {
    email: "brooke.brooks@outlook.com",
    password: "brooke456",
    role: "volunteer",
  },
  { email: "chase.kelly@gmail.com", password: "chase24", role: "volunteer" },
  { email: "paige.sanders@yahoo.com", password: "paige123", role: "volunteer" },
  { email: "trevor.price@gmail.com", password: "trevor456", role: "volunteer" },
  {
    email: "sierra.bennett@hotmail.com",
    password: "sierra24",
    role: "volunteer",
  },
  { email: "colin.wood@outlook.com", password: "colin123", role: "volunteer" },
  {
    email: "autumn.barnes@gmail.com",
    password: "autumn456",
    role: "volunteer",
  },
  { email: "blake.ross@yahoo.com", password: "blake24", role: "volunteer" },
  {
    email: "destiny.henderson@gmail.com",
    password: "destiny1",
    role: "volunteer",
  },
  {
    email: "garrett.coleman@hotmail.com",
    password: "garrett24",
    role: "volunteer",
  },
  {
    email: "sydney.jenkins@outlook.com",
    password: "sydney123",
    role: "volunteer",
  },
  { email: "travis.perry@gmail.com", password: "travis456", role: "volunteer" },
  { email: "jade.powell@yahoo.com", password: "jade24", role: "volunteer" },
  { email: "hunter.long@gmail.com", password: "hunter123", role: "volunteer" },
  {
    email: "maya.patterson@hotmail.com",
    password: "maya456",
    role: "volunteer",
  },
  {
    email: "connor.hughes@outlook.com",
    password: "connor24",
    role: "volunteer",
  },
];
// Volunteer Profiles - Complete seed data matching your Volunteer model
const volunteerSeedData = [
  {
    user_id: 1, // Assuming user IDs start from 1
    firstName: "Sarah",
    lastName: "Johnson",
    phone: "555-0101",
    dateOfBirth: "1995-03-15",
    address: "123 Main St, Dallas, TX 75201",
    emergencyContact: {
      name: "Michael Johnson",
      phone: "555-0102",
      relationship: "Brother",
    },
    bio: "Passionate about helping families in need. Experience in food distribution and community outreach.",
    profileImage: "https://randomuser.me/api/portraits/women/1.jpg",
    totalHours: 45,
    isActive: true,
  },
  {
    user_id: 2,
    firstName: "Mike",
    lastName: "Davis",
    phone: "555-0103",
    dateOfBirth: "1988-07-22",
    address: "456 Oak Ave, Richardson, TX 75080",
    emergencyContact: {
      name: "Lisa Davis",
      phone: "555-0104",
      relationship: "Wife",
    },
    bio: "Former teacher with a passion for youth mentoring and educational programs.",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    totalHours: 120,
    isActive: true,
  },
  {
    user_id: 3,
    firstName: "Emily",
    lastName: "Wilson",
    phone: "555-0105",
    dateOfBirth: "1992-11-08",
    address: "789 Pine St, Plano, TX 75023",
    emergencyContact: {
      name: "Robert Wilson",
      phone: "555-0106",
      relationship: "Father",
    },
    bio: "Healthcare professional dedicated to serving elderly communities and health awareness.",
    profileImage: "https://randomuser.me/api/portraits/women/2.jpg",
    totalHours: 89,
    isActive: true,
  },
  {
    user_id: 4,
    firstName: "John",
    lastName: "Smith",
    phone: "555-0107",
    dateOfBirth: "1985-01-30",
    address: "321 Elm St, Garland, TX 75040",
    emergencyContact: {
      name: "Mary Smith",
      phone: "555-0108",
      relationship: "Mother",
    },
    bio: "Construction worker volunteering weekends for Habitat for Humanity projects.",
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    totalHours: 156,
    isActive: true,
  },
  {
    user_id: 5,
    firstName: "Lisa",
    lastName: "Brown",
    phone: "555-0109",
    dateOfBirth: "1990-05-12",
    address: "654 Maple Dr, Irving, TX 75061",
    emergencyContact: {
      name: "James Brown",
      phone: "555-0110",
      relationship: "Husband",
    },
    bio: "Social worker specializing in family services and crisis intervention support.",
    profileImage: "https://randomuser.me/api/portraits/women/3.jpg",
    totalHours: 203,
    isActive: true,
  },
  {
    user_id: 6,
    firstName: "David",
    lastName: "Miller",
    phone: "555-0111",
    dateOfBirth: "1987-09-25",
    address: "987 Cedar Ln, Mesquite, TX 75149",
    emergencyContact: {
      name: "Susan Miller",
      phone: "555-0112",
      relationship: "Sister",
    },
    bio: "IT professional helping non-profits with technology setup and digital literacy.",
    profileImage: "https://randomuser.me/api/portraits/men/3.jpg",
    totalHours: 78,
    isActive: true,
  },
  {
    user_id: 7,
    firstName: "Jennifer",
    lastName: "Garcia",
    phone: "555-0113",
    dateOfBirth: "1993-12-03",
    address: "147 Birch St, Carrollton, TX 75006",
    emergencyContact: {
      name: "Carlos Garcia",
      phone: "555-0114",
      relationship: "Father",
    },
    bio: "Bilingual volunteer focused on immigrant services and community translation.",
    profileImage: "https://randomuser.me/api/portraits/women/4.jpg",
    totalHours: 67,
    isActive: true,
  },
  {
    user_id: 8,
    firstName: "Robert",
    lastName: "Martinez",
    phone: "555-0115",
    dateOfBirth: "1984-04-18",
    address: "258 Willow Rd, Allen, TX 75013",
    emergencyContact: {
      name: "Anna Martinez",
      phone: "555-0116",
      relationship: "Wife",
    },
    bio: "Veteran committed to supporting fellow veterans and military families.",
    profileImage: "https://randomuser.me/api/portraits/men/4.jpg",
    totalHours: 134,
    isActive: true,
  },
  {
    user_id: 9,
    firstName: "Maria",
    lastName: "Rodriguez",
    phone: "555-0117",
    dateOfBirth: "1991-08-14",
    address: "369 Spruce Ave, Frisco, TX 75034",
    emergencyContact: {
      name: "Diego Rodriguez",
      phone: "555-0118",
      relationship: "Brother",
    },
    bio: "Nurse volunteering at health clinics and community wellness events.",
    profileImage: "https://randomuser.me/api/portraits/women/5.jpg",
    totalHours: 198,
    isActive: true,
  },
  {
    user_id: 10,
    firstName: "James",
    lastName: "Taylor",
    phone: "555-0119",
    dateOfBirth: "1989-02-28",
    address: "741 Ash St, McKinney, TX 75069",
    emergencyContact: {
      name: "Patricia Taylor",
      phone: "555-0120",
      relationship: "Mother",
    },
    bio: "Chef providing cooking classes and meal preparation for homeless shelters.",
    profileImage: "https://randomuser.me/api/portraits/men/5.jpg",
    totalHours: 92,
    isActive: true,
  },
  {
    user_id: 11,
    firstName: "Anna",
    lastName: "Anderson",
    phone: "555-0121",
    dateOfBirth: "1994-06-10",
    address: "852 Poplar Dr, Lewisville, TX 75057",
    emergencyContact: {
      name: "Erik Anderson",
      phone: "555-0122",
      relationship: "Father",
    },
    bio: "College student organizing campus volunteer drives and charity events.",
    profileImage: "https://randomuser.me/api/portraits/women/6.jpg",
    totalHours: 34,
    isActive: true,
  },
  {
    user_id: 12,
    firstName: "Michael",
    lastName: "Thomas",
    phone: "555-0123",
    dateOfBirth: "1986-10-07",
    address: "963 Hickory Ln, Flower Mound, TX 75022",
    emergencyContact: {
      name: "Sarah Thomas",
      phone: "555-0124",
      relationship: "Wife",
    },
    bio: "Financial advisor offering free financial literacy workshops to underserved communities.",
    profileImage: "https://randomuser.me/api/portraits/men/6.jpg",
    totalHours: 87,
    isActive: true,
  },
  {
    user_id: 13,
    firstName: "Jessica",
    lastName: "Jackson",
    phone: "555-0125",
    dateOfBirth: "1992-01-19",
    address: "159 Walnut St, Coppell, TX 75019",
    emergencyContact: {
      name: "Mark Jackson",
      phone: "555-0126",
      relationship: "Husband",
    },
    bio: "Artist teaching art therapy sessions for children in foster care.",
    profileImage: "https://randomuser.me/api/portraits/women/7.jpg",
    totalHours: 76,
    isActive: true,
  },
  {
    user_id: 14,
    firstName: "William",
    lastName: "White",
    phone: "555-0127",
    dateOfBirth: "1983-05-23",
    address: "357 Chestnut Ave, Grapevine, TX 76051",
    emergencyContact: {
      name: "Linda White",
      phone: "555-0128",
      relationship: "Mother",
    },
    bio: "Retired firefighter volunteering for disaster relief and emergency preparedness training.",
    profileImage: "https://randomuser.me/api/portraits/men/7.jpg",
    totalHours: 245,
    isActive: true,
  },
  {
    user_id: 15,
    firstName: "Ashley",
    lastName: "Harris",
    phone: "555-0129",
    dateOfBirth: "1996-09-16",
    address: "468 Beech Dr, Euless, TX 76040",
    emergencyContact: {
      name: "Nicole Harris",
      phone: "555-0130",
      relationship: "Sister",
    },
    bio: "Marketing professional helping small nonprofits with social media and outreach.",
    profileImage: "https://randomuser.me/api/portraits/women/8.jpg",
    totalHours: 52,
    isActive: true,
  },
  {
    user_id: 16,
    firstName: "Christopher",
    lastName: "Martin",
    phone: "555-0131",
    dateOfBirth: "1988-12-11",
    address: "579 Sycamore Rd, Bedford, TX 76021",
    emergencyContact: {
      name: "Jennifer Martin",
      phone: "555-0132",
      relationship: "Wife",
    },
    bio: "Mechanic providing free car maintenance for single mothers and elderly residents.",
    profileImage: "https://randomuser.me/api/portraits/men/8.jpg",
    totalHours: 108,
    isActive: true,
  },
  {
    user_id: 17,
    firstName: "Amanda",
    lastName: "Thompson",
    phone: "555-0133",
    dateOfBirth: "1991-03-04",
    address: "680 Magnolia St, Hurst, TX 76053",
    emergencyContact: {
      name: "David Thompson",
      phone: "555-0134",
      relationship: "Father",
    },
    bio: "Librarian organizing literacy programs and reading sessions for children.",
    profileImage: "https://randomuser.me/api/portraits/women/9.jpg",
    totalHours: 145,
    isActive: true,
  },
  {
    user_id: 18,
    firstName: "Matthew",
    lastName: "Garcia",
    phone: "555-0135",
    dateOfBirth: "1987-07-21",
    address: "791 Dogwood Ave, Colleyville, TX 76034",
    emergencyContact: {
      name: "Rosa Garcia",
      phone: "555-0136",
      relationship: "Mother",
    },
    bio: "Personal trainer leading fitness programs for seniors and disability support groups.",
    profileImage: "https://randomuser.me/api/portraits/men/9.jpg",
    totalHours: 98,
    isActive: true,
  },
  {
    user_id: 19,
    firstName: "Stephanie",
    lastName: "Lee",
    phone: "555-0137",
    dateOfBirth: "1993-11-08",
    address: "813 Redwood Dr, Southlake, TX 76092",
    emergencyContact: {
      name: "Kevin Lee",
      phone: "555-0138",
      relationship: "Brother",
    },
    bio: "Photographer documenting nonprofit events and creating promotional materials pro bono.",
    profileImage: "https://randomuser.me/api/portraits/women/10.jpg",
    totalHours: 63,
    isActive: true,
  },
  {
    user_id: 20,
    firstName: "Andrew",
    lastName: "Clark",
    phone: "555-0139",
    dateOfBirth: "1985-04-15",
    address: "924 Cedar Ridge Ln, Keller, TX 76248",
    emergencyContact: {
      name: "Michelle Clark",
      phone: "555-0140",
      relationship: "Wife",
    },
    bio: "Engineer volunteering for STEM education programs in underserved schools.",
    profileImage: "https://randomuser.me/api/portraits/men/10.jpg",
    totalHours: 112,
    isActive: true,
  },
  {
    user_id: 21,
    firstName: "Nicole",
    lastName: "Lewis",
    phone: "555-0141",
    dateOfBirth: "1990-08-27",
    address: "135 Pine Valley Rd, Roanoke, TX 76262",
    emergencyContact: {
      name: "Brian Lewis",
      phone: "555-0142",
      relationship: "Husband",
    },
    bio: "Counselor providing mental health support at community centers and shelters.",
    profileImage: "https://randomuser.me/api/portraits/women/11.jpg",
    totalHours: 167,
    isActive: true,
  },
  {
    user_id: 22,
    firstName: "Joshua",
    lastName: "Walker",
    phone: "555-0143",
    dateOfBirth: "1989-12-02",
    address: "246 Oak Hill Dr, Trophy Club, TX 76262",
    emergencyContact: {
      name: "Rachel Walker",
      phone: "555-0144",
      relationship: "Sister",
    },
    bio: "Musician organizing benefit concerts and teaching music to underprivileged youth.",
    profileImage: "https://randomuser.me/api/portraits/men/11.jpg",
    totalHours: 89,
    isActive: true,
  },
  {
    user_id: 23,
    firstName: "Rachel",
    lastName: "Hall",
    phone: "555-0145",
    dateOfBirth: "1994-02-18",
    address: "357 Sunset Blvd, Westlake, TX 76262",
    emergencyContact: {
      name: "Thomas Hall",
      phone: "555-0146",
      relationship: "Father",
    },
    bio: "Environmental science student leading community garden projects and sustainability workshops.",
    profileImage: "https://randomuser.me/api/portraits/women/12.jpg",
    totalHours: 71,
    isActive: true,
  },
  {
    user_id: 24,
    firstName: "Daniel",
    lastName: "Allen",
    phone: "555-0147",
    dateOfBirth: "1986-06-14",
    address: "468 Mountain View Dr, Haslet, TX 76052",
    emergencyContact: {
      name: "Lisa Allen",
      phone: "555-0148",
      relationship: "Wife",
    },
    bio: "Paramedic teaching first aid and CPR classes to community groups.",
    profileImage: "https://randomuser.me/api/portraits/men/12.jpg",
    totalHours: 156,
    isActive: true,
  },
  {
    user_id: 25,
    firstName: "Heather",
    lastName: "Young",
    phone: "555-0149",
    dateOfBirth: "1992-10-09",
    address: "579 River Bend Rd, Azle, TX 76020",
    emergencyContact: {
      name: "Gary Young",
      phone: "555-0150",
      relationship: "Father",
    },
    bio: "Real estate agent helping homeless individuals find transitional housing and support services.",
    profileImage: "https://randomuser.me/api/portraits/women/13.jpg",
    totalHours: 94,
    isActive: true,
  },
  {
    user_id: 26,
    firstName: "Kevin",
    lastName: "King",
    phone: "555-0151",
    dateOfBirth: "1988-01-25",
    address: "680 Lakeside Dr, Lake Worth, TX 76135",
    emergencyContact: {
      name: "Amy King",
      phone: "555-0152",
      relationship: "Wife",
    },
    bio: "Electrician providing home repairs and electrical work for elderly and disabled residents.",
    profileImage: "https://randomuser.me/api/portraits/men/13.jpg",
    totalHours: 128,
    isActive: true,
  },
  {
    user_id: 27,
    firstName: "Michelle",
    lastName: "Wright",
    phone: "555-0153",
    dateOfBirth: "1991-05-11",
    address: "791 Forest Glen Dr, Weatherford, TX 76086",
    emergencyContact: {
      name: "Robert Wright",
      phone: "555-0154",
      relationship: "Father",
    },
    bio: "Veterinarian volunteering at animal shelters and providing low-cost pet care.",
    profileImage: "https://randomuser.me/api/portraits/women/14.jpg",
    totalHours: 183,
    isActive: true,
  },
  {
    user_id: 28,
    firstName: "Brian",
    lastName: "Lopez",
    phone: "555-0155",
    dateOfBirth: "1987-09-03",
    address: "813 Prairie View Ln, Springtown, TX 76082",
    emergencyContact: {
      name: "Maria Lopez",
      phone: "555-0156",
      relationship: "Mother",
    },
    bio: "Landscaper creating community gardens and maintaining public spaces for neighborhood associations.",
    profileImage: "https://randomuser.me/api/portraits/men/14.jpg",
    totalHours: 76,
    isActive: true,
  },
  {
    user_id: 29,
    firstName: "Kimberly",
    lastName: "Hill",
    phone: "555-0157",
    dateOfBirth: "1993-12-29",
    address: "924 Countryside Rd, Aledo, TX 76008",
    emergencyContact: {
      name: "Steven Hill",
      phone: "555-0158",
      relationship: "Husband",
    },
    bio: "Speech therapist working with children with disabilities at community centers.",
    profileImage: "https://randomuser.me/api/portraits/women/15.jpg",
    totalHours: 142,
    isActive: true,
  },
  {
    user_id: 30,
    firstName: "Jason",
    lastName: "Green",
    phone: "555-0159",
    dateOfBirth: "1985-04-06",
    address: "135 Heritage Dr, Hudson Oaks, TX 76087",
    emergencyContact: {
      name: "Laura Green",
      phone: "555-0160",
      relationship: "Wife",
    },
    bio: "Police officer organizing community safety programs and youth mentorship initiatives.",
    profileImage: "https://randomuser.me/api/portraits/men/15.jpg",
    totalHours: 201,
    isActive: true,
  },
  {
    user_id: 31,
    firstName: "Laura",
    lastName: "Adams",
    phone: "555-0161",
    dateOfBirth: "1990-08-22",
    address: "246 Meadowbrook Dr, Granbury, TX 76048",
    emergencyContact: {
      name: "John Adams",
      phone: "555-0162",
      relationship: "Husband",
    },
    bio: "Accountant providing free tax preparation services for low-income families.",
    profileImage: "https://randomuser.me/api/portraits/women/16.jpg",
    totalHours: 67,
    isActive: true,
  },
  {
    user_id: 32,
    firstName: "Ryan",
    lastName: "Baker",
    phone: "555-0163",
    dateOfBirth: "1989-11-17",
    address: "357 Willow Creek Dr, Cleburne, TX 76033",
    emergencyContact: {
      name: "Kelly Baker",
      phone: "555-0164",
      relationship: "Sister",
    },
    bio: "Software developer creating websites and digital tools for small nonprofits.",
    profileImage: "https://randomuser.me/api/portraits/men/16.jpg",
    totalHours: 95,
    isActive: true,
  },
  {
    user_id: 33,
    firstName: "Megan",
    lastName: "Gonzalez",
    phone: "555-0165",
    dateOfBirth: "1992-03-13",
    address: "468 Riverside Dr, Glen Rose, TX 76043",
    emergencyContact: {
      name: "Carlos Gonzalez",
      phone: "555-0166",
      relationship: "Father",
    },
    bio: "Interior designer helping families redecorate homes donated through housing programs.",
    profileImage: "https://randomuser.me/api/portraits/women/17.jpg",
    totalHours: 58,
    isActive: true,
  },
  {
    user_id: 34,
    firstName: "Tyler",
    lastName: "Nelson",
    phone: "555-0167",
    dateOfBirth: "1986-07-08",
    address: "579 Valley View Rd, Burleson, TX 76028",
    emergencyContact: {
      name: "Patricia Nelson",
      phone: "555-0168",
      relationship: "Mother",
    },
    bio: "Carpenter building wheelchair ramps and accessibility modifications for disabled residents.",
    profileImage: "https://randomuser.me/api/portraits/men/17.jpg",
    totalHours: 174,
    isActive: true,
  },
  {
    user_id: 35,
    firstName: "Crystal",
    lastName: "Carter",
    phone: "555-0169",
    dateOfBirth: "1994-10-24",
    address: "680 Hillcrest Dr, Crowley, TX 76036",
    emergencyContact: {
      name: "Michael Carter",
      phone: "555-0170",
      relationship: "Brother",
    },
    bio: "Dental hygienist providing oral health education and basic dental care at health fairs.",
    profileImage: "https://randomuser.me/api/portraits/women/18.jpg",
    totalHours: 103,
    isActive: true,
  },
  {
    user_id: 36,
    firstName: "Jacob",
    lastName: "Mitchell",
    phone: "555-0171",
    dateOfBirth: "1988-02-19",
    address: "791 Oakwood Dr, Forest Hill, TX 76119",
    emergencyContact: {
      name: "Sarah Mitchell",
      phone: "555-0172",
      relationship: "Wife",
    },
    bio: "Physical therapist offering rehabilitation services for injury recovery and mobility support.",
    profileImage: "https://randomuser.me/api/portraits/men/18.jpg",
    totalHours: 129,
    isActive: true,
  },
  {
    user_id: 37,
    firstName: "Samantha",
    lastName: "Perez",
    phone: "555-0173",
    dateOfBirth: "1991-06-15",
    address: "813 Elmwood Ave, Everman, TX 76140",
    emergencyContact: {
      name: "Diego Perez",
      phone: "555-0174",
      relationship: "Brother",
    },
    bio: "Pharmacist organizing medication management programs for elderly and chronic illness patients.",
    profileImage: "https://randomuser.me/api/portraits/women/19.jpg",
    totalHours: 86,
    isActive: true,
  },
  {
    user_id: 38,
    firstName: "Aaron",
    lastName: "Roberts",
    phone: "555-0175",
    dateOfBirth: "1993-09-01",
    address: "924 Pinehurst Dr, Kennedale, TX 76060",
    emergencyContact: {
      name: "Linda Roberts",
      phone: "555-0176",
      relationship: "Mother",
    },
    bio: "College professor tutoring high school students and adults working toward their GED.",
    profileImage: "https://randomuser.me/api/portraits/men/19.jpg",
    totalHours: 78,
    isActive: true,
  },
  {
    user_id: 39,
    firstName: "Brittany",
    lastName: "Turner",
    phone: "555-0177",
    dateOfBirth: "1990-12-26",
    address: "135 Creekside Dr, Mansfield, TX 76063",
    emergencyContact: {
      name: "James Turner",
      phone: "555-0178",
      relationship: "Father",
    },
    bio: "Event planner organizing fundraising events and charity galas for local nonprofits.",
    profileImage: "https://randomuser.me/api/portraits/women/20.jpg",
    totalHours: 147,
    isActive: true,
  },
  {
    user_id: 40,
    firstName: "Nathan",
    lastName: "Phillips",
    phone: "555-0179",
    dateOfBirth: "1987-04-12",
    address: "246 Mockingbird Ln, Arlington, TX 76001",
    emergencyContact: {
      name: "Jennifer Phillips",
      phone: "555-0180",
      relationship: "Wife",
    },
    bio: "Pilot providing emergency transportation and aerial support for disaster relief efforts.",
    profileImage: "https://randomuser.me/api/portraits/men/20.jpg",
    totalHours: 164,
    isActive: true,
  },
  {
    user_id: 41,
    firstName: "Vanessa",
    lastName: "Campbell",
    phone: "555-0181",
    dateOfBirth: "1992-07-28",
    address: "357 Bluebonnet Rd, Grand Prairie, TX 75050",
    emergencyContact: {
      name: "Robert Campbell",
      phone: "555-0182",
      relationship: "Father",
    },
    bio: "Nutritionist teaching healthy cooking classes and meal planning for families in need.",
    profileImage: "https://randomuser.me/api/portraits/women/21.jpg",
    totalHours: 91,
    isActive: true,
  },
  {
    user_id: 42,
    firstName: "Jordan",
    lastName: "Parker",
    phone: "555-0183",
    dateOfBirth: "1989-11-05",
    address: "468 Cardinal Dr, Duncanville, TX 75116",
    emergencyContact: {
      name: "Michelle Parker",
      phone: "555-0184",
      relationship: "Sister",
    },
    bio: "Social media manager helping nonprofits build online presence and donor engagement.",
    profileImage: "https://randomuser.me/api/portraits/men/21.jpg",
    totalHours: 73,
    isActive: true,
  },
  {
    user_id: 43,
    firstName: "Tiffany",
    lastName: "Evans",
    phone: "555-0185",
    dateOfBirth: "1994-03-21",
    address: "579 Rosewood Dr, DeSoto, TX 75115",
    emergencyContact: {
      name: "William Evans",
      phone: "555-0186",
      relationship: "Father",
    },
    bio: "Graphic designer creating promotional materials and awareness campaigns for social causes.",
    profileImage: "https://randomuser.me/api/portraits/women/22.jpg",
    totalHours: 54,
    isActive: true,
  },
  {
    user_id: 44,
    firstName: "Brandon",
    lastName: "Edwards",
    phone: "555-0187",
    dateOfBirth: "1986-08-16",
    address: "680 Pecan Grove Dr, Cedar Hill, TX 75104",
    emergencyContact: {
      name: "Angela Edwards",
      phone: "555-0188",
      relationship: "Wife",
    },
    bio: "Plumber providing emergency repairs and plumbing services for community housing projects.",
    profileImage: "https://randomuser.me/api/portraits/men/22.jpg",
    totalHours: 118,
    isActive: true,
  },
  {
    user_id: 45,
    firstName: "Christina",
    lastName: "Collins",
    phone: "555-0189",
    dateOfBirth: "1991-12-12",
    address: "791 Magnolia Park Dr, Lancaster, TX 75146",
    emergencyContact: {
      name: "David Collins",
      phone: "555-0190",
      relationship: "Brother",
    },
    bio: "Massage therapist offering wellness services for caregivers and nonprofit staff burnout prevention.",
    profileImage: "https://randomuser.me/api/portraits/women/23.jpg",
    totalHours: 82,
    isActive: true,
  },
  {
    user_id: 46,
    firstName: "Scott",
    lastName: "Stewart",
    phone: "555-0191",
    dateOfBirth: "1988-05-07",
    address: "813 Cottonwood Dr, Balch Springs, TX 75180",
    emergencyContact: {
      name: "Lisa Stewart",
      phone: "555-0192",
      relationship: "Mother",
    },
    bio: "Insurance agent helping disaster victims navigate claims and recovery processes.",
    profileImage: "https://randomuser.me/api/portraits/men/23.jpg",
    totalHours: 96,
    isActive: true,
  },
  {
    user_id: 47,
    firstName: "Amy",
    lastName: "Sanchez",
    phone: "555-0193",
    dateOfBirth: "1993-09-23",
    address: "924 Wildflower Ln, Seagoville, TX 75159",
    emergencyContact: {
      name: "Carlos Sanchez",
      phone: "555-0194",
      relationship: "Husband",
    },
    bio: "Occupational therapist working with children with developmental disabilities and their families.",
    profileImage: "https://randomuser.me/api/portraits/women/24.jpg",
    totalHours: 159,
    isActive: true,
  },
];
export { seedUsers, volunteerSeedData };
